language: go
go:
  - 1.3
  - 1.4
  - 1.5
  - tip

install:
  - cd $HOME
  - find . -type d
  - rm -rf $HOME/gopath/src/github.com/onsi/ginkgo
  - mv $HOME/gopath/src/github.com/{benmoss,onsi}/ginkgo
  - cd $HOME/gopath/src/github.com/onsi/ginkgo
  - go get -v -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/onsi/gomega
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace
